# Generated by Django 4.0.4 on 2022-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
